language: php
sudo: false
dist: trusty
php:
  - 8.1
  - 8.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

script:
  - composer test
